# Generated by Django 4.2.16 on 2026-04-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_category_product_short_description_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ring", "Ring"),
                    ("necklace", "Necklace"),
                    ("bracelet", "Bracelet"),
                    ("earring", "Earring"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
